/perception_ros_node:
  ros__parameters:
    color_image_topic: /camera/color/image_raw # /camera/rgb/image_color
    depth_image_topic: /camera/depth/image_raw # /camera/depth/image
    use_compressed_images: true
    color_compressed_topic: /camera/color/image_raw/compressed
    depth_compressed_topic: /camera/depth/image_raw/compressedDepth
    perception_result_topic: /perception_result
    hard_sync: false
    sync_queue_size: 1
    processing_rate_hz: 10.0
    color_bbox_topic: /camera/color/image_bbox

    # Interaction status parameters
    ## details in src/trt_infer_msgs/msg/InteractionResult.msg
    interaction_result_topic: /interaction_result
    ## yaw：表示左右转头的角度，pitch：表示上下点头的角度
    ## max_distance：表示检测的最大距离，min_distance：表示检测的最小距离
    attention_yaw_deg: 55.0
    attention_pitch_deg: 40.0
    attention_max_distance_m: 4.0
    attention_min_distance_m: 0.1

    talking_yaw_deg: 30.0
    talking_pitch_deg: 25.0
    talking_max_distance_m: 2.5
    talking_min_distance_m: 0.1
